export const ALLERGIES = [
  { id: 'peanuts', icon: 'peanuts', label: { pt: 'Amendoim', en: 'Peanuts', de: 'Erdnüsse', fr: 'Arachides', it: 'Arachidi', es: 'Cacahuetes' } },
  { id: 'tree_nuts', icon: 'tree_nuts', label: { pt: 'Nozes', en: 'Tree Nuts', de: 'Schalenfrüchte', fr: 'Fruits à coque', it: 'Frutta a guscio', es: 'Frutos secos' } },
  { id: 'dairy', icon: 'dairy', label: { pt: 'Laticínios', en: 'Dairy', de: 'Milchprodukte', fr: 'Produits laitiers', it: 'Latticini', es: 'Lácteos' } },
  { id: 'eggs', icon: 'eggs', label: { pt: 'Ovos', en: 'Eggs', de: 'Eier', fr: 'Œufs', it: 'Uova', es: 'Huevos' } },
  { id: 'gluten', icon: 'gluten', label: { pt: 'Glúten', en: 'Gluten', de: 'Gluten', fr: 'Gluten', it: 'Glutine', es: 'Gluten' } },
  { id: 'soy', icon: 'soy', label: { pt: 'Soja', en: 'Soy', de: 'Soja', fr: 'Soja', it: 'Soia', es: 'Soja' } },
  { id: 'shellfish', icon: 'shellfish', label: { pt: 'Crustáceos', en: 'Shellfish', de: 'Krustentiere', fr: 'Crustacés', it: 'Crostacei', es: 'Crustáceos' } },
  { id: 'fish', icon: 'fish', label: { pt: 'Peixe', en: 'Fish', de: 'Fisch', fr: 'Poisson', it: 'Pesce', es: 'Pescado' } },
  { id: 'sesame', icon: 'sesame', label: { pt: 'Gergelim', en: 'Sesame', de: 'Sesam', fr: 'Sésame', it: 'Sesamo', es: 'Sésamo' } },
  { id: 'corn', icon: 'corn', label: { pt: 'Milho', en: 'Corn', de: 'Mais', fr: 'Maïs', it: 'Mais', es: 'Maíz' } },
  { id: 'sulfites', icon: 'sulfites', label: { pt: 'Sulfitos', en: 'Sulfites', de: 'Sulfite', fr: 'Sulfites', it: 'Solfiti', es: 'Sulfitos' } },
  { id: 'mustard', icon: 'mustard', label: { pt: 'Mostarda', en: 'Mustard', de: 'Senf', fr: 'Moutarde', it: 'Senape', es: 'Mostaza' } },
  { id: 'fragrance', icon: 'fragrance', label: { pt: 'Fragrâncias', en: 'Fragrance', de: 'Duftstoffe', fr: 'Parfums', it: 'Fragranze', es: 'Fragancias' } },
  { id: 'essential_oils', icon: 'essential_oils', label: { pt: 'Óleos essenciais', en: 'Essential Oils', de: 'Ätherische Öle', fr: 'Huiles essentielles', it: 'Oli essenziali', es: 'Aceites esenciales' } },
  { id: 'latex', icon: 'latex', label: { pt: 'Látex', en: 'Latex', de: 'Latex', fr: 'Latex', it: 'Lattice', es: 'Látex' } },
  { id: 'nickel', icon: 'nickel', label: { pt: 'Níquel', en: 'Nickel', de: 'Nickel', fr: 'Nickel', it: 'Nichel', es: 'Níquel' } },
  { id: 'lanolin', icon: 'lanolin', label: { pt: 'Lanolina', en: 'Lanolin', de: 'Lanolin', fr: 'Lanoline', it: 'Lanolina', es: 'Lanolina' } },
  { id: 'formaldehyde', icon: 'formaldehyde', label: { pt: 'Formaldeído', en: 'Formaldehyde', de: 'Formaldehyd', fr: 'Formaldéhyde', it: 'Formaldeide', es: 'Formaldehído' } },
  { id: 'parabens', icon: 'parabens', label: { pt: 'Parabenos', en: 'Parabens', de: 'Parabene', fr: 'Parabènes', it: 'Parabeni', es: 'Parabenos' } },
  { id: 'sulfates', icon: 'sulfates', label: { pt: 'Sulfatos', en: 'Sulfates', de: 'Sulfate', fr: 'Sulfates', it: 'Solfati', es: 'Sulfatos' } },
  { id: 'dyes', icon: 'dyes', label: { pt: 'Corantes', en: 'Dyes', de: 'Farbstoffe', fr: 'Colorants', it: 'Coloranti', es: 'Colorantes' } },
  { id: 'wool', icon: 'wool', label: { pt: 'Lã', en: 'Wool', de: 'Wolle', fr: 'Laine', it: 'Lana', es: 'Lana' } },
];
