const colors = {
  primary: '#16A75A',
  primaryDark: '#0A6334',
  primaryLight: '#E2F7EA',
  primaryBg: '#F6F3EB',
  accent: '#E8991C',
  accentDark: '#A6610B',
  accentLight: '#FBEFCF',
  forest: '#0E1B14',
  darkSurface: '#0E1B14',
  navy: '#0E1B14',
  navyDeep: '#06110C',
  navyMid: '#143524',
  headerBg: '#0E1B14',
  headerText: '#FFFFFF',
  headerMuted: 'rgba(234,241,236,0.70)',
  aboutCardBg: '#0E1B14',
  aboutCardBorder: '#06110C',
  background: '#F6F3EB',
  backgroundSecondary: '#ECE7DA',
  card: '#FFFFFF',
  glass: 'rgba(255,255,255,0.82)',
  text: '#121814',
  textLight: '#5A6A63',
  textMuted: '#7C8B84',
  border: '#E2DBC9',
  safe: '#128A4B',
  safeLight: '#E2F7EA',
  safeDark: '#06311C',
  caution: '#C8790F',
  cautionLight: '#FBEFCF',
  cautionDark: '#A6610B',
  danger: '#D6453B',
  dangerLight: '#FBE6E3',
  dangerDark: '#C13B30',
  white: '#FFFFFF',
  black: '#000000',
  overlay: 'rgba(14,27,20,0.80)',
  footerScrim: 'rgba(246,243,235,0.94)',
};

const strings = {
  en: {
    welcome: {
      title: 'NovaQI',
      tagline: 'Snap your plate. Track everything.',
      subtitle: 'Photograph your plate for instant calories and macros, track your body automatically, and log every meal and workout — all matched to your diet.',
      start: 'Start Tracking',
      feature_photo_label: 'Snap your plate',
      feature_photo_detail: 'Instant calories & macros from a photo',
      feature_ai_label: 'Automatic body tracking',
      feature_ai_detail: 'Weight, BMI, body composition — from photos',
      feature_result_label: 'All in your diet',
      feature_result_detail: 'Meals, water, workouts — matched to vegan, halal & more',
    },
    auth: { tagline: "Know what's in everything" },
    home: {
      title: 'NovaQI',
      header_question: 'What are we checking today?',
      scan_subtitle: 'Food, cosmetics, clothing, cleaning products',
    },
    profile_setup: {
      how_do_you_eat: "What's your diet?",
      allergy_subtitle: 'Covers food, cosmetics, hygiene, and clothing',
    },
    scan: { analyzing_subtitle: 'NovaQI AI is reading the ingredients' },
    result: {
      safe: 'OK',
      safe_subtitle: 'Looks good for your profile',
      caution_subtitle: 'Check before using',
      not_safe_subtitle: 'Not suitable for your profile',
    },
    profile: {
      about: 'About NovaQI',
      about_text: 'Scan anything. Know instantly.',
    },
    errors: { no_api_key: 'The NovaQI API URL is not configured in the app.' },
  },
  pt: {
    welcome: {
      title: 'NovaQI',
      tagline: 'Fotografe o seu prato. Acompanhe tudo.',
      subtitle: 'Fotografe o seu prato para calorias e macros instantâneos, acompanhe o seu corpo automaticamente e registe cada refeição e treino — tudo alinhado com a sua dieta.',
      start: 'Começar a Acompanhar',
      feature_photo_label: 'Fotografe o prato',
      feature_photo_detail: 'Calorias e macros instantâneos por foto',
      feature_ai_label: 'Corpo acompanhado automaticamente',
      feature_ai_detail: 'Peso, IMC, composição corporal — por foto',
      feature_result_label: 'Tudo na sua dieta',
      feature_result_detail: 'Refeições, água, treinos — alinhados com vegan, halal e mais',
    },
    auth: { tagline: 'Saiba o que tem em tudo' },
    home: {
      title: 'NovaQI',
      header_question: 'O que vamos verificar hoje?',
      scan_subtitle: 'Alimentos, cosméticos, roupas, produtos de limpeza',
    },
    profile_setup: {
      how_do_you_eat: 'Qual é a sua dieta?',
      allergy_subtitle: 'Inclui alimentos, cosméticos, higiene e roupas',
    },
    scan: { analyzing_subtitle: 'IA do NovaQI está lendo os ingredientes' },
    result: {
      safe: 'OK',
      safe_subtitle: 'Adequado ao seu perfil',
      caution_subtitle: 'Verifique antes de usar',
      not_safe_subtitle: 'Não adequado ao seu perfil',
    },
    profile: {
      about: 'Sobre o NovaQI',
      about_text: 'Escaneie qualquer coisa. Saiba na hora.',
    },
    errors: { no_api_key: 'A URL da API do NovaQI não está configurada no app.' },
  },
  de: {
    welcome: {
      title: 'NovaQI',
      tagline: 'Foto vom Teller. Alles im Blick.',
      subtitle: 'Fotografiere deinen Teller für sofortige Kalorien und Makros, verfolge deinen Körper automatisch und protokolliere jede Mahlzeit und jedes Training — alles auf deine Ernährung abgestimmt.',
      start: 'Tracking starten',
      feature_photo_label: 'Foto vom Teller',
      feature_photo_detail: 'Sofortige Kalorien & Makros per Foto',
      feature_ai_label: 'Automatische Körperverfolgung',
      feature_ai_detail: 'Gewicht, BMI, Körperzusammensetzung — per Foto',
      feature_result_label: 'Alles für deine Ernährung',
      feature_result_detail: 'Mahlzeiten, Wasser, Training — abgestimmt auf vegan, halal & mehr',
    },
    auth: { tagline: 'Wisse was in allem steckt' },
    home: {
      title: 'NovaQI',
      header_question: 'Was prüfen wir heute?',
      scan_subtitle: 'Lebensmittel, Kosmetik, Kleidung, Reinigungsprodukte',
    },
    profile_setup: {
      how_do_you_eat: 'Was ist deine Ernährung?',
      allergy_subtitle: 'Umfasst Lebensmittel, Kosmetik, Hygiene und Kleidung',
    },
    scan: { analyzing_subtitle: 'NovaQI KI liest die Zutaten' },
    result: {
      safe: 'OK',
      safe_subtitle: 'Passt zu deinem Profil',
      caution_subtitle: 'Vor der Verwendung prüfen',
      not_safe_subtitle: 'Nicht für dein Profil geeignet',
    },
    profile: {
      about: 'Über NovaQI',
      about_text: 'Scanne alles. Wisse sofort.',
    },
    errors: { no_api_key: 'Die NovaQI API-URL ist nicht in der App konfiguriert.' },
  },
  fr: {
    welcome: {
      title: 'NovaQI',
      tagline: 'Photographiez votre assiette. Suivez tout.',
      subtitle: "Photographiez votre assiette pour des calories et macros instantanées, suivez votre corps automatiquement et enregistrez chaque repas et entraînement — le tout adapté à votre régime.",
      start: 'Commencer le suivi',
      feature_photo_label: 'Photographiez votre assiette',
      feature_photo_detail: 'Calories et macros instantanées par photo',
      feature_ai_label: 'Suivi corporel automatique',
      feature_ai_detail: 'Poids, IMC, composition corporelle — par photo',
      feature_result_label: 'Tout selon votre régime',
      feature_result_detail: 'Repas, eau, entraînements — adaptés au vegan, halal et plus',
    },
    auth: { tagline: "Sachez ce qu'il y a dans tout" },
    home: {
      title: 'NovaQI',
      header_question: "Que vérifions-nous aujourd'hui?",
      scan_subtitle: 'Aliments, cosmétiques, vêtements, nettoyants',
    },
    profile_setup: {
      how_do_you_eat: 'Quel est votre régime?',
      allergy_subtitle: 'Comprend aliments, cosmétiques, hygiène et vêtements',
    },
    scan: { analyzing_subtitle: "L'IA NovaQI lit les ingrédients" },
    result: {
      safe: 'OK',
      safe_subtitle: 'Convient à votre profil',
      caution_subtitle: 'Vérifier avant utilisation',
      not_safe_subtitle: 'Ne convient pas à votre profil',
    },
    profile: {
      about: 'À propos de NovaQI',
      about_text: 'Scannez tout. Sachez instantanément.',
    },
    errors: { no_api_key: "L'URL de l'API NovaQI n'est pas configurée dans l'app." },
  },
  it: {
    welcome: {
      title: 'NovaQI',
      tagline: 'Fotografa il piatto. Traccia tutto.',
      subtitle: "Fotografa il tuo piatto per calorie e macro istantanee, monitora il tuo corpo automaticamente e registra ogni pasto e allenamento — tutto in base alla tua dieta.",
      start: 'Inizia a tracciare',
      feature_photo_label: 'Fotografa il piatto',
      feature_photo_detail: 'Calorie e macro istantanee da una foto',
      feature_ai_label: 'Monitoraggio corporeo automatico',
      feature_ai_detail: 'Peso, BMI, composizione corporea — da foto',
      feature_result_label: 'Tutto nella tua dieta',
      feature_result_detail: 'Pasti, acqua, allenamenti — in base a vegano, halal e altro',
    },
    auth: { tagline: "Sappi cosa c'è in tutto" },
    home: {
      title: 'NovaQI',
      header_question: 'Cosa controlliamo oggi?',
      scan_subtitle: 'Cibo, cosmetici, abbigliamento, prodotti per la pulizia',
    },
    profile_setup: {
      how_do_you_eat: 'Qual è la tua dieta?',
      allergy_subtitle: 'Include cibo, cosmetici, igiene e abbigliamento',
    },
    scan: { analyzing_subtitle: "L'IA NovaQI sta leggendo gli ingredienti" },
    result: {
      safe: 'OK',
      safe_subtitle: 'Adatto al tuo profilo',
      caution_subtitle: 'Controlla prima di usare',
      not_safe_subtitle: 'Non adatto al tuo profilo',
    },
    profile: {
      about: 'Informazioni su NovaQI',
      about_text: 'Scansiona tutto. Sapilo subito.',
    },
    errors: { no_api_key: "L'URL dell'API NovaQI non è configurata nell'app." },
  },
  es: {
    welcome: {
      title: 'NovaQI',
      tagline: 'Fotografía tu plato. Controla todo.',
      subtitle: 'Fotografía tu plato para calorías y macros instantáneas, controla tu cuerpo automáticamente y registra cada comida y entrenamiento — todo según tu dieta.',
      start: 'Empezar a controlar',
      feature_photo_label: 'Fotografía tu plato',
      feature_photo_detail: 'Calorías y macros instantáneas por foto',
      feature_ai_label: 'Control corporal automático',
      feature_ai_detail: 'Peso, IMC, composición corporal — por foto',
      feature_result_label: 'Todo en tu dieta',
      feature_result_detail: 'Comidas, agua, entrenamientos — según vegano, halal y más',
    },
    auth: { tagline: 'Conoce lo que hay en todo' },
    home: {
      title: 'NovaQI',
      header_question: '¿Qué verificamos hoy?',
      scan_subtitle: 'Alimentos, cosméticos, ropa, productos de limpieza',
    },
    profile_setup: {
      how_do_you_eat: '¿Cuál es tu dieta?',
      allergy_subtitle: 'Incluye alimentos, cosméticos, higiene y ropa',
    },
    scan: { analyzing_subtitle: 'La IA de NovaQI está leyendo los ingredientes' },
    result: {
      safe: 'OK',
      safe_subtitle: 'Adecuado para tu perfil',
      caution_subtitle: 'Verificar antes de usar',
      not_safe_subtitle: 'No adecuado para tu perfil',
    },
    profile: {
      about: 'Acerca de NovaQI',
      about_text: 'Escanea todo. Sábelo al instante.',
    },
    errors: { no_api_key: 'La URL de la API de NovaQI no está configurada en la app.' },
  },
};

export default {
  id: 'novaqi',
  name: 'NovaQI',
  namePrefix: 'Nova',
  nameSuffix: 'QI',
  domain: 'novaqi.app',
  basePath: '/novaqi',
  fonts: {
    heading: 'Manrope_800ExtraBold',
    headingMed: 'Manrope_700Bold',
    body: 'PlusJakartaSans_500Medium',
    bodyBold: 'PlusJakartaSans_700Bold',
    mono: 'SpaceMono_400Regular',
    monoBold: 'SpaceMono_700Bold',
  },
  colors,
  strings,
};
