const colors = {
  primary: '#E8A020',
  primaryDark: '#B87600',
  primaryLight: '#FFF3D6',
  primaryBg: '#FFFBEB',
  accent: '#E8A020',
  accentDark: '#B87600',
  accentLight: '#FFF3D6',
  forest: '#1E1B4B',
  darkSurface: '#1E1B4B',
  navy: '#1E1B4B',
  navyDeep: '#13112E',
  navyMid: '#2D2A5E',
  headerBg: '#1E1B4B',
  headerText: '#FFFFFF',
  headerMuted: 'rgba(255,255,255,0.70)',
  aboutCardBg: '#1E1B4B',
  aboutCardBorder: '#13112E',
  background: '#F8F7F4',
  backgroundSecondary: '#F0EEE8',
  card: '#FFFFFF',
  glass: 'rgba(255,255,255,0.82)',
  text: '#1A1918',
  textLight: '#6B6B72',
  textMuted: '#9A9AA6',
  border: '#E4E2DC',
  safe: '#059669',
  safeLight: '#ECFDF5',
  safeDark: '#065F46',
  caution: '#D97706',
  cautionLight: '#FFFBEB',
  cautionDark: '#92400E',
  danger: '#DC2626',
  dangerLight: '#FEF2F2',
  dangerDark: '#991B1B',
  white: '#FFFFFF',
  black: '#000000',
  overlay: 'rgba(19,17,46,0.80)',
};

const strings = {
  en: {
    welcome: {
      title: 'NovaQI',
      tagline: 'Scan anything. Know instantly.',
      subtitle: 'Scan any product — food, cosmetics, clothing, cleaning — and get an instant verdict for your profile.',
      start: 'Start Scanning',
      feature_photo_label: 'Scan anything',
      feature_photo_detail: 'Barcode, label, or ingredient list',
      feature_ai_label: 'AI reads it all',
      feature_ai_detail: 'Ingredients, sensitivities, additives',
      feature_result_label: 'Instant verdict',
      feature_result_detail: 'OK, caution or avoid — in seconds',
    },
    auth: { tagline: "Know what's in everything" },
    home: {
      title: 'NovaQI',
      header_question: 'What are we checking today?',
      scan_subtitle: 'Food, cosmetics, clothing, cleaning products',
    },
    profile_setup: {
      how_do_you_eat: "What's your diet?",
      allergy_subtitle: 'Covers food, cosmetics, hygiene, and clothing',
    },
    scan: { analyzing_subtitle: 'NovaQI AI is reading the ingredients' },
    result: {
      safe: 'OK',
      safe_subtitle: 'Looks good for your profile',
      caution_subtitle: 'Check before using',
      not_safe_subtitle: 'Not suitable for your profile',
    },
    profile: {
      about: 'About NovaQI',
      about_text: 'Scan anything. Know instantly.',
    },
    errors: { no_api_key: 'The NovaQI API URL is not configured in the app.' },
  },
  pt: {
    welcome: {
      title: 'NovaQI',
      tagline: 'Escaneie qualquer coisa. Saiba na hora.',
      subtitle: 'Escaneie qualquer produto — alimentos, cosméticos, roupas, limpeza — e receba um veredicto instantâneo.',
      start: 'Começar a Escanear',
      feature_photo_label: 'Escaneie tudo',
      feature_photo_detail: 'Código de barras, rótulo ou ingredientes',
      feature_ai_label: 'IA lê tudo',
      feature_ai_detail: 'Ingredientes, sensibilidades, aditivos',
      feature_result_label: 'Veredicto instantâneo',
      feature_result_detail: 'OK, atenção ou evitar — em segundos',
    },
    auth: { tagline: 'Saiba o que tem em tudo' },
    home: {
      title: 'NovaQI',
      header_question: 'O que vamos verificar hoje?',
      scan_subtitle: 'Alimentos, cosméticos, roupas, produtos de limpeza',
    },
    profile_setup: {
      how_do_you_eat: 'Qual é a sua dieta?',
      allergy_subtitle: 'Inclui alimentos, cosméticos, higiene e roupas',
    },
    scan: { analyzing_subtitle: 'IA do NovaQI está lendo os ingredientes' },
    result: {
      safe: 'OK',
      safe_subtitle: 'Adequado ao seu perfil',
      caution_subtitle: 'Verifique antes de usar',
      not_safe_subtitle: 'Não adequado ao seu perfil',
    },
    profile: {
      about: 'Sobre o NovaQI',
      about_text: 'Escaneie qualquer coisa. Saiba na hora.',
    },
    errors: { no_api_key: 'A URL da API do NovaQI não está configurada no app.' },
  },
  de: {
    welcome: {
      title: 'NovaQI',
      tagline: 'Scanne alles. Wisse sofort.',
      subtitle: 'Scanne jedes Produkt — Lebensmittel, Kosmetik, Kleidung, Reinigung — und erhalte sofort ein Urteil.',
      start: 'Scannen starten',
      feature_photo_label: 'Alles scannen',
      feature_photo_detail: 'Barcode, Etikett oder Zutaten',
      feature_ai_label: 'KI liest alles',
      feature_ai_detail: 'Zutaten, Empfindlichkeiten, Zusatzstoffe',
      feature_result_label: 'Sofortiges Urteil',
      feature_result_detail: 'OK, Vorsicht oder meiden — in Sekunden',
    },
    auth: { tagline: 'Wisse was in allem steckt' },
    home: {
      title: 'NovaQI',
      header_question: 'Was prüfen wir heute?',
      scan_subtitle: 'Lebensmittel, Kosmetik, Kleidung, Reinigungsprodukte',
    },
    profile_setup: {
      how_do_you_eat: 'Was ist deine Ernährung?',
      allergy_subtitle: 'Umfasst Lebensmittel, Kosmetik, Hygiene und Kleidung',
    },
    scan: { analyzing_subtitle: 'NovaQI KI liest die Zutaten' },
    result: {
      safe: 'OK',
      safe_subtitle: 'Passt zu deinem Profil',
      caution_subtitle: 'Vor der Verwendung prüfen',
      not_safe_subtitle: 'Nicht für dein Profil geeignet',
    },
    profile: {
      about: 'Über NovaQI',
      about_text: 'Scanne alles. Wisse sofort.',
    },
    errors: { no_api_key: 'Die NovaQI API-URL ist nicht in der App konfiguriert.' },
  },
  fr: {
    welcome: {
      title: 'NovaQI',
      tagline: 'Scannez tout. Sachez instantanément.',
      subtitle: "Scannez n'importe quel produit — aliments, cosmétiques, vêtements, nettoyants — et obtenez un verdict instantané.",
      start: 'Commencer à scanner',
      feature_photo_label: 'Scannez tout',
      feature_photo_detail: 'Code-barres, étiquette ou ingrédients',
      feature_ai_label: "L'IA lit tout",
      feature_ai_detail: 'Ingrédients, sensibilités, additifs',
      feature_result_label: 'Verdict instantané',
      feature_result_detail: 'OK, attention ou éviter — en secondes',
    },
    auth: { tagline: "Sachez ce qu'il y a dans tout" },
    home: {
      title: 'NovaQI',
      header_question: "Que vérifions-nous aujourd'hui?",
      scan_subtitle: 'Aliments, cosmétiques, vêtements, nettoyants',
    },
    profile_setup: {
      how_do_you_eat: 'Quel est votre régime?',
      allergy_subtitle: 'Comprend aliments, cosmétiques, hygiène et vêtements',
    },
    scan: { analyzing_subtitle: "L'IA NovaQI lit les ingrédients" },
    result: {
      safe: 'OK',
      safe_subtitle: 'Convient à votre profil',
      caution_subtitle: 'Vérifier avant utilisation',
      not_safe_subtitle: 'Ne convient pas à votre profil',
    },
    profile: {
      about: 'À propos de NovaQI',
      about_text: 'Scannez tout. Sachez instantanément.',
    },
    errors: { no_api_key: "L'URL de l'API NovaQI n'est pas configurée dans l'app." },
  },
  it: {
    welcome: {
      title: 'NovaQI',
      tagline: 'Scansiona tutto. Sapilo subito.',
      subtitle: "Scansiona qualsiasi prodotto — cibo, cosmetici, abbigliamento, pulizie — e ottieni un verdetto istantaneo.",
      start: 'Inizia a scansionare',
      feature_photo_label: 'Scansiona tutto',
      feature_photo_detail: 'Codice a barre, etichetta o ingredienti',
      feature_ai_label: "L'IA legge tutto",
      feature_ai_detail: 'Ingredienti, sensibilità, additivi',
      feature_result_label: 'Verdetto istantaneo',
      feature_result_detail: 'OK, attenzione o evitare — in secondi',
    },
    auth: { tagline: "Sappi cosa c'è in tutto" },
    home: {
      title: 'NovaQI',
      header_question: 'Cosa controlliamo oggi?',
      scan_subtitle: 'Cibo, cosmetici, abbigliamento, prodotti per la pulizia',
    },
    profile_setup: {
      how_do_you_eat: 'Qual è la tua dieta?',
      allergy_subtitle: 'Include cibo, cosmetici, igiene e abbigliamento',
    },
    scan: { analyzing_subtitle: "L'IA NovaQI sta leggendo gli ingredienti" },
    result: {
      safe: 'OK',
      safe_subtitle: 'Adatto al tuo profilo',
      caution_subtitle: 'Controlla prima di usare',
      not_safe_subtitle: 'Non adatto al tuo profilo',
    },
    profile: {
      about: 'Informazioni su NovaQI',
      about_text: 'Scansiona tutto. Sapilo subito.',
    },
    errors: { no_api_key: "L'URL dell'API NovaQI non è configurata nell'app." },
  },
  es: {
    welcome: {
      title: 'NovaQI',
      tagline: 'Escanea todo. Sábelo al instante.',
      subtitle: 'Escanea cualquier producto — alimentos, cosméticos, ropa, limpieza — y obtén un veredicto instantáneo.',
      start: 'Empezar a escanear',
      feature_photo_label: 'Escanea todo',
      feature_photo_detail: 'Código de barras, etiqueta o ingredientes',
      feature_ai_label: 'La IA lo lee todo',
      feature_ai_detail: 'Ingredientes, sensibilidades, aditivos',
      feature_result_label: 'Veredicto instantáneo',
      feature_result_detail: 'OK, precaución o evitar — en segundos',
    },
    auth: { tagline: 'Conoce lo que hay en todo' },
    home: {
      title: 'NovaQI',
      header_question: '¿Qué verificamos hoy?',
      scan_subtitle: 'Alimentos, cosméticos, ropa, productos de limpieza',
    },
    profile_setup: {
      how_do_you_eat: '¿Cuál es tu dieta?',
      allergy_subtitle: 'Incluye alimentos, cosméticos, higiene y ropa',
    },
    scan: { analyzing_subtitle: 'La IA de NovaQI está leyendo los ingredientes' },
    result: {
      safe: 'OK',
      safe_subtitle: 'Adecuado para tu perfil',
      caution_subtitle: 'Verificar antes de usar',
      not_safe_subtitle: 'No adecuado para tu perfil',
    },
    profile: {
      about: 'Acerca de NovaQI',
      about_text: 'Escanea todo. Sábelo al instante.',
    },
    errors: { no_api_key: 'La URL de la API de NovaQI no está configurada en la app.' },
  },
};

export default {
  id: 'novaqi',
  name: 'NovaQI',
  namePrefix: 'Nova',
  nameSuffix: 'QI',
  domain: 'novaqi.app',
  basePath: '/novaqi',
  fonts: {
    heading: 'Syne_800ExtraBold',
    headingMed: 'Syne_700Bold',
    body: 'PlusJakartaSans_500Medium',
    bodyBold: 'PlusJakartaSans_700Bold',
  },
  colors,
  strings,
};
